spring:
  profiles:
    include: env
  jpa:
    hibernate:
      ddl-auto: update
    
server:
  servlet:
    session:
      timeout: 15m
      cookie:
        http-only: true
        # secure: true
        # domain: localhost
        same-site: lax

